### ISSUE TITLE
Infer type based on isNothing

### ISSUE THREAD

**Issue by eh-am** [true-myth/true-myth#279]
Hey!
Here, the type `string` is inferred when we check using `isJust`.
However, I was expecting the opposite to work, ie the `else` block of `isNothing`.

![image](https://user-images.githubusercontent.com/6951209/147943386-a900947f-4bfd-47cf-a07a-1c7a3544d381.png)
https://stackblitz.com/edit/typescript-yivps1?file=index.ts

**Comment by chriskrycho** [comment]
Huh! Thanks for reporting. I'm surprised this doesn't work as well, and I would expect it to. I'll try to poke at it sometime soon!

**Comment by chriskrycho** [comment]
Okay, following up very quickly, I tried this out [on a TypeScript playground][p], and it narrows correctly. Unfortunately, the Stackblitz container is simply refusing to load the package for me, so I'm not sure what's happening there. Can you try to get a reproduction in some other context (even just a tiny repo)? Could be it's part of your `tsconfig.json` settings or something!

[p]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAWQIYE8BGBTOAzKERwDkMUArhgLQgowAWA9CKpoQNwBQ7ANhvAQLyJmGAHQRsACgBEACQxcuEAIRSAlB3bBscCSBHAAzgDkIdYADsA5qrgBvdnDh6Abki7l2AXzjyDWe44ubh6e7EA

**Comment by eh-am** [comment]
Sure!
https://github.com/eh-am/true-myth-inferr-type-error

**Comment by eh-am** [comment]
Sure! 
https://github.com/eh-am/true-myth-inferr-type-error


```
❯ npm run start

> true-myth-inferr-type-error@1.0.0 start /home/eduardo/projects/true-myth-inferr-type-error
> tsc --noEmit index.ts

index.ts:14:5 - error TS2339: Property 'value' does not exist on type 'Maybe<string>'.
  Property 'value' does not exist on type 'Nothing<string>'.

14   m.value;
       ~~~~~


Found 1 error.
```

**Comment by chriskrycho** [comment]
Ah, yep, that’s helpful. As I suspected, the key is configuration. TypeScript can only successfully narrow this for you when you're using `strictNullChecks`. (Which, given you're looking at this library, I would *very strongly* assume you want.

You can see this by just adding a `tsconfig.json` file with these contents:

```json
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

You could also see it via CLI:

```sh
$ npm run tsc -- --noEmit --strictNullChecks true index.ts
```

As to *why*: I’m not actually totally sure why the narrowing isn’t working when `strictNullChecks` is off. (I have no good intuitions about non-`strict` type checking at this point, because I have basically *only* worked with strict mode for the last half decade!)
