### ISSUE TITLE
Idea: `Lift`

### ISSUE THREAD

**Issue by MarcNq** [true-myth/true-myth#32]
Hi and thanks for this library!

It would be nice to have a `lift` function in the library that ensures a value T is a Maybe<T>, without creating a Maybe<Maybe<T>>:

```typescript
lift<T>(a: T | Maybe<T>): Maybe<T> {
    return Maybe.isInstance( value )
        ? value
        : Maybe.of( value )
}
```

**Comment by chriskrycho** [comment]
Hi @MarcNq – interesting suggestion! Can you give an example of where you’d use it? (I’m certainly not opposed; it’s just not a thing I’ve ever felt a need for!)

**Comment by MarcNq** [comment]
Hi @chriskrycho!

Upon thinking about it, I realise mine may be quite an edge case, so feel free to close this issue.

I'm currently using True Myth *without* Typescript, in a project that possibly will use Typescript in the future (and if not, this library works awesomely anyway).
Because I can't rely on types yet, I opted to do defensive programming in case some values were plain values instead of Maybes, because the whole point of Maybe is to avoid crashes, not provoke them.

The function in particular was `allProperties`, similar to `Maybe.all`, but for dictionaries:

```javascript
// object of maybes -> maybe object
export const allProperties = R.pipe(
    R.toPairs,
    R.map( ( [ key, value ] ) => (
        Maybe.all( ...[ Maybe.of( key ), lift( value ) ] ) ) // Here I use my lift
    ),
    maybePairs => Maybe.all( ...maybePairs ),
    Maybe.map( R.fromPairs ),
)
```

In a Typescript, this object would be enforced to be a `Map<string, Maybe<T>>`, thus no need for this check.

Also, I'm not sure "lift" would be the appropriate name for the function.

I wanted to open an issue afterwards for this `allProperties` method... What do you think?

Thanks!

**Comment by chriskrycho** [comment]
So a couple thoughts here:

1. I'm super glad this is proving useful for you even without TS! However, one of our design goals for this was to play specifically in the space where you *can* rely on TS, rather than on runtime checks (because [Folktale](https://folktale.origamitower.com) covers that space really well!). So I'm hesitant for that reason.

2. Even if we decide we do want this functionality, I'd be inclined *against* `lift` because that has a specific meaning in typed functional programming contexts, where you "lift" a function into a context like `Maybe` or `Result` or (in Haskell or similar) some generic type-class context for things like Applicative and Functor and Monad (OH MY). So if we decide to go down this road, we can broaden the type of `Maybe.of` from `of<T>(t: T | null | undefined): Maybe<T>` to `of<T>(t: t | Maybe<T> | null | undefined): Maybe<T>` and it should Just Work™.

In that case, I *believe* you could rewrite your example like this:

```ts
R.pipe(
  R.toPairs,
  R.map(([key, value]) => Maybe.tuple([Maybe.of(key), Maybe.of(value)])),
  pairs => Maybe.all(...pairs),
  Maybe.map(R.fromPairs),
);
```

And then `Maybe.of` would just be:

```ts
function of<T>(t: T | Maybe<T> | null | undefined): Maybe<T> {
  return isVoid(t)
    ? nothing()
    : isInstance(t)
      ? t
      : just(t);
}
```

And I think that for scenarios where you have a mix of `Maybe` and not on a dictionary or object like this, that could actually be useful for TS users as well!

@bmakuh what are your thoughts on this?

**Comment by MarcNq** [comment]
I was just thinking,

Does a type Maybe<Maybe<T>> make sense?
If it does, I don't think `.of` should lose the ability to produce it.
If it doesn't, I think all the type Maybe should enforce this restriction. But then there would be no sense in the existence of both map and chain.

Does any other library enforce this? I think pure FP languages allow you to have this type, and then again, if it is typed it's not really inconvenient.

**Comment by bmakuh** [comment]
Yeah, so `Maybe<Maybe<T>>` is a viable type, which is why you can construct it with `of`. There is certainly convenience in a flat constructor like what you have, but we wouldn't want to eliminate the possibility of a nested maybe. 

Part of the confusion is that JavaScript itself is confused about what should happen here: while `Array<Array<T>>` is a perfectly viable type, `Promise<Promise<T>>` is not, so it makes it hard to have an intuition about what should happen with maybes.

**Comment by chriskrycho** [comment]
Following up on this, I realized for the points you both just raised that we definitely wouldn’t want to change the behavior of `of`. I’m also inclined to say that because this is kind of an edge case, it doesn’t make sense to push handling for it into the library, especially since it’s straightforward to work around or to use `andThen`/`flatMap` to resolve the nesting. Mostly because we’re trying to walk a fine line of being idiomatic to use *in TypeScript*, with the assumption that we have the type checker around to help, and therefore with the most minimal set of runtime checks possible (shoving as much as possible into the type system).

**Comment by chriskrycho** [comment]
I've chewed on this for a while, and given both @bmakuh's astute comment and my own reflections on it, I'm going to close it and not implement. That said: I appreciate the thoughtful suggestion, and I hope the library continues to be useful for you!
