### ISSUE TITLE
maybefy, a function that wraps an async function to make it return a Result

### ISSUE THREAD

**Issue by dandrei** [true-myth/true-myth#35]
Curious what you think of this pattern. This function takes an async function and returns another function that resolves the Promise and wraps the resolved output inside a `Result`. Type information for params and returned values is preserved.

```ts
export function maybefy<F extends (...args: any[]) => Promise<any>>(fn: F) {
    type PromisedGeneric<P> = P extends Promise<infer G> ? G : never;
    type Promised = PromisedGeneric<ReturnType<F>>;

    return async (...args: Parameters<F>): Promise<Result<Promised, Error>> => {
        try {
            const result = await fn(...args);
            return result === null || result === undefined
                ? Result.err(Error("N/A"))
                : Result.ok(result);
        } catch (e) {
            return Result.err(e);
        }
    };
}
```

Use case: write code that interacts with APIs in a classical way instead of having it directly return `Result.ok` or `Result.err`.

**Comment by chriskrycho** [comment]
Sorry for the delay – I just saw this as I was at EmberConf the past few days.

I think the pattern in general is good! However, I'd tackle it a bit differently. If the function is an `async`/`Promise`-returning function, we can accomplish the same thing with the traditional `.then` and writing a function of type `(error: unknown) => E` in the `.catch`:

```ts
type Promised<P> = P extends Promise<infer Q> ? Q : never;
type AsyncFn = (...args: any[]) => Promise<any>;
type PromisedReturn<F extends AsyncFn> = Promised<ReturnType<F>>;
type SafelyPromised<F extends AsyncFn, E> = Promise<Result<PromisedReturn<F>, E>>;

function forPromiseOr<F extends AsyncFn, E>(
  error: E,
  fn: F
): (...args: Parameters<F>) => SafelyPromised<F, E> {
  return (...args: Parameters<F>) =>
    fn(...args)
      .then(Result.ok)
      .catch(_ => Result.err(error)) as SafelyPromised<F, E>;
}

function forPromiseOrElse<F extends AsyncFn, E>(
  buildErr: (error: unknown) => E,
  fn: F
): (...args: Parameters<F>) => SafelyPromised<F, E> {
  return (...args: Parameters<F>) =>
    fn(...args)
      .then(Result.ok)
      .catch(e => Result.err(buildErr(e))) as SafelyPromised<F, E>;
}
```

(I used these names to match the convention in the library more generally; at a minimum I think you'd want `resultify` over `maybefy` given what you're doing!)

Notice:

- these are identical to what you're doing except that they're ready to handle the `E` type as well, and they *don't* use `try`/`catch` (the only reason I did that in `Result.tryOr` and `Result.tryOrElse` is that there's literally no other way you *can* do it)

- the cast is here so we don't have a bunch of extra type parameters floating around; the cast is *safe* but TS loses track of what the result type actually is – it happens in the `try`/`catch` approach as well; inspect the type of `result` in the `const result = ...` declaration to see that

From my perspective at least, this is a *lot* cleaner and more in line with the way the rest of the codebase works and the way that True Myth-using code is written in general.

---

In terms of whether something like this will ever actually land in True Myth natively, my answer is "probably not" because *if* we decided to build this kind of thing, we'd be far more inclined to build an actual `Task`/`Future`/`Eventual` abstraction (see #25).

Thanks for the thoughtful suggestion, though! I'm going to close this but we welcome further conversation on this thread!
