### ISSUE TITLE
Relying on typescript

### ISSUE THREAD

**Issue by katywings** [true-myth/true-myth#43]
First and foremost: Amazing project you got here! Keep up the good work!

I have a question regarding your info, that this library doesnt rely on runtime checks. What I dont understand is: say i write code with this library in typescript and someday 3 years in the future decide to stop using typescript, in which areas will i miss out with true-myth then? Which areas are only covered by ts? Example: if a maybe is nothing or result, thats checked in the runtime right, (because I cant think of a static way 😅)? So true-myth is not just a typescript "typing" layer without any runtime checks? I could use it with just js and still would profit? 🤔

I am referring to:
> to have zero runtime cost beyond simple object construction and function invocation
> to lean heavily on TypeScript to enable all of the above

**Comment by chriskrycho** [comment]
Hey, thanks for the kind words and the thoughtful question!

To answer the question: a few of the other libraries out there will go out of their way to give you helpful diagnostics and errors if you "do the wrong thing" in plain-old JS. All of that adds run-time overhead. (Sanctuary goes so far as to provide a tutorial on how to remove all those helpers in a custom build if you want, which is kind of neat as a way to have help during dev but strip it out for production builds!)

True Myth, instead, will just blow up if you do the wrong thing. So here's an example of a thing which, as of 3.0, the types won't let you do:

```ts
const selector = ".greeting";
Maybe.of(selector)
  .map(document.querySelector.bind(document)) // …can be `undefined` 😱 
  .map(el => el.innerHTML); // boom
```

That's totally valid JS, but *not* allowed by the types. Sanctuary or Folktale would give you feedback at runtime (or possibly fix it for you at runtime? I don't recall for sure). In True Myth, we disallow it at *compile* time: you can't have a `Maybe<undefined>`! But if you pull out TS, then you don't have anything guarding you against that… so you'll be able to invoke a function which has that bad outcome, and the final map call will result in our old friend:

> TypeError: undefined is not an object (evaluating 'el.innerHTML')

This is because functions like `map` *assume* that type-checking is in place and that you *can't* end up in a place where you try to call a function on something which is `null` or `undefined`—we treat it as a *bug* if you can.

Hopefully that helps clear it up a bit.

In terms of impact if you drop TS in 3 years: everything will still work, but then you'd be responsible for making sure you don't accidentally construct a `Maybe<null>` yourself, and you'd only find out by way of runtime errors when calling `map` or `unwrap` or the like. That's pretty normal for JS, though; it's just that we're not doing anything *extra* to help the way the other libraries do! And on that note it's worth noting that if I were working in a plain-JS project that *couldn't* move to TS for whatever reason, I'd almost certainly use Folktale: it's a *great* library.

**Comment by chriskrycho** [comment]
(Closing this, since it's just a discussion issue, but please feel free to ask further questions, etc.!)

**Comment by katywings** [comment]
Hello Chris

Thanks a lot for your detailled answer, which definitly resolved my question :D!
