### ISSUE TITLE
Maybe.get nested property on object

### ISSUE THREAD

**Issue by eikooc** [true-myth/true-myth#46]
This is a feature request. Right now it is possible to get a first level property of a _Maybe_, but it would be really useful to access deeply nested properties.

E.g. Right now it is possible to do: `maybeObj.get('title')`, but I would like to be able to do: `maybeObj.get('deep.property.a')`

This would be really useful when receiving data from an IO operation where we don't know if it conforms to the data we expect.

**Comment by chriskrycho** [comment]
Ah, yeah, I totally get that—I've wanted it as well at times! There's a tradeoff here: as it is, `Maybe.get` (and `Maybe.property`) can check whether the key you're looking at *actually exists* on the object you're looking at. If we made it able to handle just *any* structure out of the gate, that property goes away.

There is a workaround for this today: define the type you're working with as a `Dict` type like this:

```ts
interface Dict<T = unknown> {
  [key: string]: T | void;
}
```

Then you can do:

```ts
let aDict: Dict = { foo: { bar: { baz: 'hi' } } };
let maybeQuux = just(aDict).get('foo.bar.quux');
```

Now, in a lot of cases that's *not* what you want to do, because you want to say "This thing *should* have a specific shape, and that shape isn't an arbitrary bag of data." So for that case, I think there is totally value in going ahead and adding something that traverses a key path like that.

One design consideration: since things *do* work correctly in  the `Dict` scenario, I would lean toward passing an array of keys instead of the `.` syntax. It'd be something like this (though I'm not sure on the name):

```ts

let theThing: { foo?: { bar?: { baz?: string } } } = { foo: { bar: { baz: 'hi' } } };
let maybeBaz = just(theThing).getDeep(['foo', 'bar', 'baz']);
```

While that's slightly more verbose, it can be *type-safe* with regard to the object shape you *expect*.

**Comment by eikooc** [comment]
Thank you for the thorough answer.

Although I can't get your example to work, it gives me a _Nothing_ even if I try to `.get('foo.bar.baz')`.

With regards to creating a new function called `getDeep`, would it not be possible to just let `get` receive extra arguments? `function get(a, ...rest)` then the API would just be `maybeFoo.get('foo')` and `maybeBaz.get('foo', 'bar', 'baz')`

**Comment by chriskrycho** [comment]
Oh, that's because I'm dumb and forgot something really important but often confusing in JS (and have been working more closely recently with code that uses `get` differently). `Maybe.get` is treating `'foo.bar.baz'` as a string key on an object there, i.e. it's trying to resolve this:

```ts
const jsIsAmazing = {
  ['foo.bar.baz']: 'oh my',
};
```

And unfortunately, there's no *good* way to support *both*.

---

I'll mull on a variadic argument type like that, but off the top of my head I *think* the answer is: you could do it, but it couldn't be type-safe in anyway. That is: there'd be no way to check whether the keys you passed were valid keys on the nested objects you passed in. That in turn would mean you wouldn't get back the correct type inside the `Maybe` at the end and would have to cast it.

**Comment by chriskrycho** [comment]
I'm going to go ahead and close this because I don't think we actually *need* it, and I think most of the time it's better to use explicit operations dealing with nested `Maybe`s if you have them, and to *avoid* having nested `Maybe`s in the first place as much as possible. Thanks again for opening it!
