### ISSUE TITLE
Unable to bundle with microbundle

### ISSUE THREAD

**Issue by DaviDevMod** [true-myth/true-myth#481]
I am unable to bundle with [microbundle](https://github.com/developit/microbundle), which doesn't really have configuration options.
I tried removing the *.cjs* output and also [*true-myth* altogether](https://github.com/developit/microbundle/wiki/How-Microbundle-decides-which-dependencies-to-bundle#2-i-dont-want-to-bundle-a-dependency) from the bundle, but I am still unable to build my package.

Here is the repo: https://github.com/DaviDevMod/focus-trap/tree/dev/packages/focus-trap

When trying to build, I get:

> (rpt2 plugin) Error: /focus-trap/packages/focus-trap/src/trap-actions.ts(1,33): semantic error TS2307: Cannot find module 'true-myth/result' or its corresponding type declarations.

I am aware of [these requirements](https://github.com/true-myth/true-myth/issues/416#issuecomment-1215083533) which are all met by my setup, while removing `true-myth` from the bundle should address what was outlined in [this comment](https://github.com/true-myth/true-myth/discussions/461#discussioncomment-4070673).

As suggested by @chriskrycho I tried using a 5.x release and it works :tada: 

It would be nice, though, if I could eventually be able to use the latest *true-myth* release.

**Comment by chriskrycho** [comment]
Failed to reply to this – it’s still on my mental radar, but maintenance on this repo is pushed lower on our priority lists. I will try to take a look at some point. Thanks for the clear report! Can you link to a specific commit in that repo to reproduce, in case/as you work on it?

**Comment by chriskrycho** [comment]
Two notes here:

1. I can indeed trivially reproduce this with `microbundle`.

2. But the problem is that `microbundle` ultimately uses `rollup-plugin-typescript2`, which [currently forces](https://github.com/ezolenko/rollup-plugin-typescript2/blob/f6db59613a66f58c48310aa8fa785951970b5d6d/README.md#some-compiler-options-are-forced) the `moduleResolution` mode to `node`, which is not compatible with ES module emit.

Net, this is a `microbundle` and `rollup-plugin-typescript2` problem, and there's not really anything we can do about it in the current _status quo_—`microbundle` will not work with *any* pure ESM package. I’m still pondering whether we revisit that question (though honestly the longer we go into the future the less likely it is), but at least we know that that's the issue!

**Comment by DaviDevMod** [comment]
@chriskrycho thank you so much for the insights.
The JS ecosystem will eventually catch up and in the meantime one can always use a 5.x release.
I think I'll go for bundler that allows for more freedom of movement though.
Keep it up!

**Comment by chriskrycho** [comment]
FYI, this may be unblocked by #567. ESM conversion across the ecosystem is very, very slow, so I'm unblocking it. Wheeeeee.
