### ISSUE TITLE
CommonJS (`require`) imports do not work as documented

### ISSUE THREAD

**Issue by JesterXL** [true-myth/true-myth#53]
`'Maybe' refers to a value, but is being used as a type here`

```typescript
const someFunc = (event:Object): Maybe<string> =>
```

What am I doing wrong? I have a suspicion my default `tsconfig.json` isn't good enough for Node?

**Comment by JesterXL** [comment]
I'm an idiot, I missed the subtly in the docs. I had:
```typescript
const { Maybe } = require('true-myth/maybe')
```

But it should be this:
```typescript
const { Maybe } = require('true-myth')
```
MY BAD!

**Comment by JesterXL** [comment]
Ok, nevermind, now that the library works, I'm still getting this error in TypeScript.

**Comment by JesterXL** [comment]
I read: https://github.com/true-myth/true-myth/issues/17

It seems I cannot use `const { Maybe } = require('true-myth')`. I tried with `import` and it works. Why doesn't it work with `require`?

**Comment by chriskrycho** [comment]
Thanks for reporting this!

The problem is that we don't have the `esModuleInterop` compiler option enabled (because it's viral and forces all downstream consumers to *also* do likewise), which is what's required for `= require`-style/CommonJS imports to work.

TS does some magic to make `import` work correctly for CJS modules, so you can generally just write normal ES Module import statements and be off to the races. (And hey: *Soon™* that'll work on Node proper, as well! `--experimental-modules` on Node 12 works pretty well already!) I'm going to convert this to a docs issue. If you feel like opening a PR to fix it, I'd welcome that; otherwise I'll try to get to it in the next week or so!
