### ISSUE TITLE
Result cannot handle undefined

### ISSUE THREAD

**Issue by lo1tuma** [true-myth/true-myth#607]
The following code doesn’t cause any type error:

```ts
function foo(): Result<undefined, string> {
    return Result.ok(undefined);
}

const result = foo();

if (result.isOk) {
    result.value
}
```

The inferred type of `result.value` is `undefined`. But it is actually an object (an instance of `Unit`).

----------------

In my use case I have a generic validation function which takes and input of `unknown` and a schema which is a generic type parameter. The return type of this validation function is the type of the validated result of the schema. The schema can also  handle `undefined` but unfortunately `Result` can’t.

------------------

I see two options here:

* Disallow `undefined` as a possible type for the first `Result` type parameter
* Allow `undefined` and don’t map it to `Unit` automatically

**Comment by chriskrycho** [comment]
Interesting; that’s definitely a bug. I never thought about this, because we've always implicitly assumed the use of `Result` and `Maybe` together, but especially in a world with pervasive optional chaining and nullish coalescing, I can see why someone might reach for `Result` but *not* `Maybe`.

I think it would be pretty straightforward to forbid `undefined` and `null` in the `T` position (just put a `T extends {}` constraint on all the relevant clauses), but it is actually not obvious to me what the most desirable behavior here is, precisely because folks might want to use `Result` but *not* `Maybe`, as in your motivating scenario. HMMMM.

We will think on and chat about this; my immediate intuition here is that we might be able to handle this (and honestly treat it as a bug fix from a release POV!) where the behavior looks something like this:

- `Result.ok()` → `Result<Unit, E>`
- `Result.ok(undefined)` → `Result<undefined, E>`

I would need to see what would be required to make that work, but I think it’s actually just a matter of tweaking the implementation and types *very* slightly, and I would be perfectly comfortable with that change: when you produce `undefined` (or a union of something *with* `undefined`) you will always be doing so explicitly; the “implicit” path would always still produce `Unit` and therefore be safer.

@bmakuh, thoughts?

**Comment by bmakuh** [comment]
Yeah, I mean `Result.ok(undefined)` is definitely weird, but it doesn’t really seem like a problem. So I guess that the suggestion of treating an explicit `undefined` differently from an implicit one (no parameter provided) seems like the right direction. @lo1tuma would you be interested in drafting a PR to fix this?

**Comment by chriskrycho** [comment]
@bmakuh I already opened a PR, actually! I’ll merge it and release it!

**Comment by chriskrycho** [comment]
Released as part of [v7.1.0](https://github.com/true-myth/true-myth/releases/tag/v7.1.0).

**Comment by lo1tuma** [comment]
Yeah, having to possibility to distinguish between explicit `undefined` and missing parameter would definitely solve the issue for me use-case. 

@chriskrycho Thank you for addressing this so fast.

**Comment by chriskrycho** [comment]
@lo1tuma glad I was *able* to get a quick turnaround. As evidenced by it taking 3 weeks for me to see your comment, it's not a given. 😂
