### ISSUE TITLE
ap() and currying

### ISSUE THREAD

**Issue by thewilkybarkid** [true-myth/true-myth#66]
I've tried to follow the doc examples of `ap()` and lodash's `curry()`, but run into type problems:

```typescript
import { curry } from 'lodash';
import { Result } from 'true-myth';

const add = (a: number, b: number): number => a + b;
const curriedAdd = curry(add);

console.log(
  Result.of(curriedAdd)
    .ap(Result.of(1)).ap(Result.of(5))
    .unsafelyUnwrap()
);

const merge3Strs = (a: string, b: string, c: string): string => `${a} ${b} ${c}`;
const curriedMerge = curry(merge3Strs);

console.log(
  Result.of<typeof curriedMerge, string>(curriedMerge)
    .ap(Result.of('a')).ap(Result.of('b')).ap(Result.of('c'))
    .unsafelyUnwrap()
);
```

The first usage has:

```
The 'this' context of type 'Result<CurriedFunction2<number, number, number>, unknown>' is not assignable to method's 'this' of type 'Result<(a: number) => number, unknown>'.
```

and the second:

```
The 'this' context of type 'Result<CurriedFunction3<string, string, string, string>, string>' is not assignable to method's 'this' of type 'Result<(a: string) => string, string>'.
```

but the code works correctly in both places.

Has lodash's typing changed so that it's now incompatible, or is there something wrong here?

**Comment by chriskrycho** [comment]
Hey @thewilkybarkid, thanks for the report and sorry for the delay in responding—thought I had notifications set up correctly for this repo but apparently not! I’ll take a look sometime soon. I would guess lodash’s types changed, because there are features in TS from the last year or so (much more recent than when the docs were written) which allowed lodash to be much more robust—but also changed inference.

I’ve been meaning to take a pass on freshening up this library soon anyway, so this and a couple other issues should get resolved then!

**Comment by chriskrycho** [comment]
Okay, so I've dug into this and our docs will need to be updated here!

It appears that none of the major libraries out there (lodash, ramda, etc.) yet have types which will *correctly* handle currying using the features introduced in TS 4.0 for variadic tuple types, which are what would be necessary to make this work. Though they do it in different ways, lodash's and ramda's types both introduce intermediate representation types which are callable, but which don't work as *normal* function types in a way that TS's inference can preserve here. That's partly because both of them go out of their way to support "placeholder" versions of currying where you can partially apply *arbitrary arguments*, which honestly I think is bonkers. 😂 

I'll think on the best way to handle this.

**Comment by CrossEye** [comment]
Hi Ramda author here, and I'm curious to hear why the placeholder currying is bonkers.

There is controversy among the Ramda principle authors about the use of placeholders, so your certainly not alone, but I would love to hear arguments from outside.

The advantage, of course is being able to do this:

```js
const bar = foo (1, __, 3)
// ...
bar (42) //~> foo (1, 42. 3)
```

Ramda tries to arrange its parameters in logical order so that there's less need for this, and one can just use simpler currying.  But there are times when there are multiple reasonable orders.  Should it be `find (needle, haystack)` or `find (haystack, needle)`.  The partial application of one parameter to either of these is useful in certain circumstances.  Of course, `flip` works for the binary case, there's no obvious variant for polyadic functions.

So is this bonkers on it's own, or is it mostly bonkers when trying to make things work with the more statically typed Typescript?

(Or maybe it's just me who's bonkers.  There's a lot of evidence there...)

**Comment by CrossEye** [comment]
Sorry if I sounded offended.  If "bonkers" was the worst thing Ramda got called today, it would be a very good day, indeed!  :wink:  I was just curious about the reason.

Ramda suffers from envy of better FP languages.  "If we only had Haskell's sections,"  "If we could simply use placeholders like in Erlang," etc.  When we can do something that helps scratch that itch, we tend to do so.  Transducers were probably a mistake, but the hot new thing coming out of Closure, and seemed like a good fit for our adolescent library.  The placeholders is in that in-between state, maybe not a real mistake, but never a really clear fit either.  I keep thinking we'll do something like lodash's `rearg` and let that combine with simpler currying to handle such cases.

In any case, although I haven't actually used true-myth yet, I've enjoyed watching it develop.  Thanks for all your effort.
