### ISSUE TITLE
Why isn't curry1 a main export?

### ISSUE THREAD

**Issue by risingBirdSong** [true-myth/true-myth#68]
I tried to import curry like so ....

import {curry1} from "true-myth";

but found it isn't exported there, it is exported from utils though, like so,

import { curry1 } from "true-myth\\src\\utils";

Is there a reason curry isn't a main export?

**Comment by chriskrycho** [comment]
Hey @risingBirdSong – it's not exported because it's not designed for general-purpose currying in JS (for that we'd recommend something like lodash or Ramda), only for internal use so that we can avoid forcing *everyone* who uses this to pay the cost of one of those libraries.

I'll see if I can get TypeDoc to exclude it from the API docs at https://true-myth.js.org so that this confusion doesn't come up again in the future!

**Comment by chriskrycho** [comment]
Updated docs via e68d77c. This *should* be excluded from the docs going forward.

**Comment by risingBirdSong** [comment]
Ok cool thanks for the info, I'll use Ramda :)
