### ISSUE TITLE
`toString()` incorrectly stringify objects

### ISSUE THREAD

**Issue by nullndr** [true-myth/true-myth#758]
The output of the following code:

```typescript
console.log(toString(ok({ foo: "bar" })));
```

Will be `Ok([object Object])` instead of `Ok({ foo: "bar" })` like the README.md suggest [here](https://github.com/true-myth/true-myth/blob/8ae5cdefc9d7be430649764aada75b05f8fb48f4/README.md?plain=1#L181).

This is due to the implementation of the `has()` and `safeToString()` functions:

```typescript
function has<T, K extends PropertyKey>(value: T, key: K): value is T & { [Key in K]: unknown } {
  return typeof value === 'object' && value !== null && key in value;
}

export function safeToString(value: unknown): string {
  if (has(value, 'toString') && typeof value['toString'] === 'function') {
    const fnResult = value.toString();
    return typeof fnResult === 'string' ? fnResult : JSON.stringify(value);
  } else {
    return JSON.stringify(value);
  }
}
```

Since the objects that inherit from `Object.prototype` will inherit the default implementation of `Object.prototype.toString()`, `safeToString()` will eventually results in the defaults `[object Object]`, `[object Set]` and `[object Map]`.

I would like to suggest a stricter (but more verbose) `safeToString()` version:

```typescript
export function safeToString(value: unknown): string {
  if(value === null) {
    return "null";
  }

  if(value === undefined) {
    return "undefined";
  }

  if(Array.isArray(value)) {
    return safeToStringArray(value);
  }

  if(value instanceof Map) {
    return safeToStringMap(value);
  }

  if(value instanceof Set) {
    return safeToStringSet(value);
  }

  ...

  return JSON.stringify(value);
}
```

May I open a PR if you like this approach?

**Comment by chriskrycho** [comment]
Thanks for opening this! Our docs are definitely incorrect here, so we definitely need to fix that.

Past that, I am also thinking on whether we want to add more custom behavior on `toString()`. For one thing, doing so would be a breaking change, since the implementation we have has been the way it is for a *very* long time now (even if documented incorrectly). For another, doing so would actually take us *away* from normal JavaScript behavior. One of our design heuristics has been to provide specifically and only the functionality needed for the library itself—because that keeps the library both smaller and easier to compose with other things.

My *gut* reaction here, then, is not to add additional behavior here but instead *only* to fix the docs. Types which want custom printing from `toString` should implement it themselves. That way we never end up in a precedence fight about how we implement it (with some kind of checking against the prototype chain, presumably) and how someone *else* implements it. 😅

I will let @bmakuh chime in before making a final call here!

**Comment by nullndr** [comment]
Thank you

**Comment by bmakuh** [comment]
Yeah I think my main question is whether this is blocking you in some way, or if you just happened to notice that the docs weren't correct. I don't know that I'm entirely opposed to breaking changes if there's a compelling reason, but otherwise I think Chris is probably right that we should err on the side of normal behavior

**Comment by nullndr** [comment]
I just found this incongruency with the docs while testing it

**Comment by bmakuh** [comment]
OK got it. Yeah in that case I do think the better fix is to adjust the docs rather than the code.
